### PR TITLE
ci: remove arm32 builds

### PR DESCRIPTION
**Pull request by xoxys**

### CODE REVIEW

**Comment by fmoc** [comment]
What's the reason for this change? @dschmidt mentioned Drone made some changes with regards to ARM support, but I have not looked into it yet.

**Comment by xoxys** [comment]
Please see the internal chat for discussion. But you don't build multiarch images for this repo anyway?

**Comment by fmoc** [comment]
Not at the moment, no. We'll need ARM images once we start building Linux stuff on ARM hosts, though, I guess. But I don't think anyone expects GUI tools on 32-bit ARM any more.

**Review by fmoc — APPROVED** [review]

**Comment by fmoc** [comment]
Thanks!

**Pull request merged**
